### ISSUE TITLE
`yarn test:integration` does not respect jest command line arguments

### ISSUE THREAD

**Issue by andrewgordstewart** [magmo/apps#103]
I want to, for example, run` yarn test:integration some-specific-file.ts`, like I can with jest.

**Comment by lalexgap** [comment]
This is an issue with `magmo-devtools`. I haven't found a way to pass into command line arguments when running jest programmatically.

**Comment by lalexgap** [comment]
I've created this under tooling board since I believe this an issue with magmo-devtools here https://zube.io/magmo/tooling/c/20
