### ISSUE TITLE
Deploy TTT to production

### ISSUE THREAD

**Issue by kerzhner** [magmo/apps#123]
The pieces are:
* Domain name.
* GC storage for the app.
* Firebase realtime database.
* Google Cloud Build pipeline.

**Comment by geoknee** [comment]
My suggestion for domain names would be

RPS: rps.magmo.com
TTT: ttt.magmo.com

Some sort of game menu at apps.magmo.com or games.magmo.com. 

We would also want to update a) the magmo website and b) the wallet landing page at wallet,magmo.com, to either point to the new game menu or at least feature both apps.
