### ISSUE TITLE
Withdraw fails after challenge expires until next block is mined

### ISSUE THREAD

**Issue by kerzhner** [magmo/apps#126]
Repro steps:
- Player challenges
- Player waits for challenge to expire
- Player tries to withdraw funds.

The error:
{type: "WALLET.CHALLENGING.CHALLENGE_COMPLETE"}
main.8cf3f180.chunk.js:1 Error: JsonRpcEngine - response has no error or result for request:
{
  "method": "eth_estimateGas",
  "params": [
    {
      "from": "0x731d94003be596Dfb195972C586547aCC88cB607",
      "to": "0x65B978c12b91dC4D4C357b350860233356795a1a",
      "data": "0x65a7c9d1000000000000000000000000b6c23eaab499bcc3fa022882ec6725a9907f1ddb000000000000000000000000b6c23eaab499bcc3fa022882ec6725a9907f1ddbc2e33e95105ede31c711ac149733d9841cfda8ce2a5d276ed22302b4c12da5fc000000000000000000000000000000000000000000000000000000000000001cd4c2deda4147c6770a29e2bfc861ef76438e56d99b059782bea32fd9ed9aeb062d60bfefa9ed2ccfd7d806bd47552865c2c70619f623955a30bb4e487aa2421e"
    }
  ],
  "id": 618655296,
  "jsonrpc": "2.0"
}
    at inpage.js:1
    at n (inpage.js:1)
    at o (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
    at u (inpage.js:1)
    at a (inpage.js:1)
    at inpage.js:1
    at inpage.js:1
    at inpage.js:1
t.transactionSender @ main.8cf3f180.chunk.js:1
P @ 2.479e6bb9.chunk.js:1
w @ 2.479e6bb9.chunk.js:1
(anonymous) @ 2.479e6bb9.chunk.js:1
Promise.then (async)
U @ 2.479e6bb9.chunk.js:1
(anonymous) @ 2.479e6bb9.chunk.js:1
D @ 2.479e6bb9.chunk.js:1
P @ 2.479e6bb9.chunk.js:1
w @ 2.479e6bb9.chunk.js:1
(anonymous) @ 2.479e6bb9.chunk.js:1
o @ 2.479e6bb9.chunk.js:1
c @ 2.479e6bb9.chunk.js:1
a @ 2.479e6bb9.chunk.js:1
(anonymous) @ 2.479e6bb9.chunk.js:1
D @ 2.479e6bb9.chunk.js:1
P @ 2.479e6bb9.chunk.js:1
w @ 2.479e6bb9.chunk.js:1
Promise.then (async)
U @ 2.479e6bb9.chunk.js:1
(anonymous) @ 2.479e6bb9.chunk.js:1
D @ 2.479e6bb9.chunk.js:1
P @ 2.479e6bb9.chunk.js:1
v @ 2.479e6bb9.chunk.js:1
L @ 2.479e6bb9.chunk.js:1
D @ 2.479e6bb9.chunk.js:1
P @ 2.479e6bb9.chunk.js:1
w @ 2.479e6bb9.chunk.js:1
(anonymous) @ 2.479e6bb9.chunk.js:1
D @ 2.479e6bb9.chunk.js:1
P @ 2.479e6bb9.chunk.js:1
w @ 2.479e6bb9.chunk.js:1
a @ 2.479e6bb9.chunk.js:1
put @ 2.479e6bb9.chunk.js:1
(anonymous) @ 2.479e6bb9.chunk.js:1
emit @ 2.479e6bb9.chunk.js:1
(anonymous) @ 2.479e6bb9.chunk.js:1
dispatch @ VM37:1
(anonymous) @ 2.479e6bb9.chunk.js:1
approvalAction @ main.8cf3f180.chunk.js:1
value @ 2.479e6bb9.chunk.js:1
(anonymous) @ 2.479e6bb9.chunk.js:1
f @ 2.479e6bb9.chunk.js:1
(anonymous) @ 2.479e6bb9.chunk.js:1
A @ 2.479e6bb9.chunk.js:1
C @ 2.479e6bb9.chunk.js:1
M @ 2.479e6bb9.chunk.js:1
N @ 2.479e6bb9.chunk.js:1
Sn @ 2.479e6bb9.chunk.js:1
La @ 2.479e6bb9.chunk.js:1
Ut @ 2.479e6bb9.chunk.js:1
Cn @ 2.479e6bb9.chunk.js:1
Ba @ 2.479e6bb9.chunk.js:1
kn @ 2.479e6bb9.chunk.js:1

**Comment by kerzhner** [comment]
Stuck on this screen: ![Screen Shot 2019-01-30 at 6.32.17 PM.png](https://zube.io/files/magmo/27c8c302f582669963f2a272157efa2a-screen-shot-2019-01-30-at-6-32-17-pm.png)

**Comment by lalexgap** [comment]
@kerzhner I've retried this a couple times and I've always gotten the option to retry the transaction. Could you nuke your cache and retry?

The underlying issue is that we have to wait for a block to be mined before the contract will consider the challenge expired. ( see https://ethereum.stackexchange.com/questions/19360/now-keyword-in-solidity)

**Comment by kerzhner** [comment]
@alexgap, after clearing the cache, I am seeing the expected behavior (transaction fails, but I am able to retry)
