### ISSUE TITLE
Winner should be able to avoid playing again

### ISSUE THREAD

**Issue by geoknee** [magmo/apps#128]
Either player should be able to resign instead of playing again, should they wish.

Either player should be able to challenge if they are waiting for the other to play again (and the other player has also not resigned).

**Comment by kerzhner** [comment]
Pushing to next week's spring

**Comment by geoknee** [comment]
Right now I believe the two resting states have the `player` field (either 0 or 1) as well as the `noughts` and `crosses` field. In the first round, this is probably enough to work out who played last. Generally though, there would not be a way to infer which `player` is which `marker`. We may need to put that information in the actual position/statement.

Related to this: TTT’s `validTransition` probably needs revisiting to make sure it works with this flow (in case someone challenges after sending a resting statement). i.e. we would want `validTransition(resting, resting)` to return `true`.

**Comment by geoknee** [comment]
The current philosophy is that you can resign if and only if it is your turn, and challenge if and only if is their turn. Of course this is unavoidable in ForceMove. 

The important flow that is not fully implemented is to receive a 'Resting' or 'PlayAgainMeSecond' and respond with a 'Conclude'. 

In RPS if you win on *their* move, you have the option to resign and avoid playing again. If you win on your own move, the only option is to challenge or play again, even if the other player sends a Resting state.

In TTT you can only win on your own move, so the only way to avoid playing again is to challenge. Again, even if a PlayAgainMeSecond move has been received, you are forced to play again.

**Comment by geoknee** [comment]
This is less important for RPS than for TTT, since the winner can simply play again and then resign immediately. In TTT, if you click play again then you have already committed and cannot exit without penalty.

**Comment by geoknee** [comment]
In future we may (or may not) want to allow resignations at any time, and let the wallet handle the implications. For example, upon a resign action it could provide the user with options:

If your turn: 
- Send Conclude immediately

if not your turn
- Commit to Send Conclude as soon as *any* position is received
- Immediately Send Conclude as an alternative move to your previous move (i.e. without increasing turnNum), and explain that this may adversely affect how much money you will end up getting
then wait for a response, and nudge the user to challenge if no response is forthcoming after some time out. 

But in general there is a choice here about how much of this is handled by the wallet vs the app.
