### ISSUE TITLE
Unify our approach to testing contracts

### ISSUE THREAD

**Issue by geoknee** [magmo/apps#162]
@andrewgordstewart and I investigated some problems I was having in ttt with flickering tests. 

The following pattern:

https://github.com/magmo/apps/blob/9f2ea6ca8a1b62cc1c25c8cfe936a34834823508/packages/rps/src/contract-tests/rock-paper-scissors.test.ts#L55

can sometimes (often?) result in a *promise* being checked for *truthy-ness*, meaning that test will pass regardless of what the promise might resolve to. I fixed it in ttt:

https://github.com/magmo/apps/blob/9f2ea6ca8a1b62cc1c25c8cfe936a34834823508/packages/tictactoe/src/contract-tests/ttt-game.test.ts#L54

but something similar needs to be done in wallet and rps. 

Furthermore, there is scope for folding this pattern as well as this one https://github.com/magmo/apps/blob/9f2ea6ca8a1b62cc1c25c8cfe936a34834823508/packages/tictactoe/src/contract-tests/ttt-game.test.ts#L87, into a helper function in magmo-devtools which is the imported into the apps.

**Comment by andrewgordstewart** [comment]
Minor point of clarification:
>[the expectation] can sometimes (often?) result in a _promise_ being checked for _truthy-ness_

It _always_ results in a promise being checked for truthyness. In the situations above, however, `whateverContract.validTransition` either resolves to `true` or throws an error, due to the implementation of the smart contract's `validTransition` function, so when an error isn't thrown, the test suite still isn't asserting that the returned value was true.

**Comment by andrewgordstewart** [comment]
>as well as [this one](https://github.com/magmo/apps/blob/9f2ea6ca8a1b62cc1c25c8cfe936a34834823508/packages/tictactoe/src/contract-tests/ttt-game.test.ts#L87) into a helper function in magmo-devtools which is the imported into the apps.

via something like
```
async function expectRevert(fn, msg) {
  expect.assertions(1);
  await expect(fn()).rejects.toThrowError(msg);
}
```
