### ISSUE TITLE
You get stuck on the login page if you dismiss the modal

### ISSUE THREAD

**Issue by tomclose** [magmo/apps#181]
In the gif:
1. The first time the modal doesn't appear and I'm stuck on the login page. Seems to be the behaviour described in https://github.com/magmo/apps/issues/170
2. I refresh the page to get around the first issue. When the modal appears, I dismiss it (e.g. not realising it's important). I'm then stuck on the login page.

![login-problem](https://user-images.githubusercontent.com/29596/52529472-da4a3380-2ca6-11e9-8160-b4da24df1b8a.gif)

**Comment by geoknee** [comment]
![screen recording 2019-02-10 at 12 20 42](https://user-images.githubusercontent.com/1833419/52533700-98190480-2d2f-11e9-9520-ac9e8ff1af3b.gif)

**Comment by geoknee** [comment]
We now wait for the wallet to be initialized before firing the login success action:

https://github.com/magmo/apps/blob/a3abaf0adcdd4b587b9dbbf97f49bcddd1edb39b/packages/tictactoe/src/redux/login/saga.ts#L42 

Commenting that line seems to restore desired behaviour -- is it that we cannot (should not) initialize the wallet if it is already initialized? I would have thought we want to initialize the wallet just once when the site loads, and not every time we want to check the login status. We could either move the initialization command elsewhere (e.g. loginRootSaga) or replace it with appropriate conditional logic (if wallet is not initialized, then initialize, else don't bother).

**Comment by geoknee** [comment]
Also:

https://github.com/magmo/apps/blob/a3abaf0adcdd4b587b9dbbf97f49bcddd1edb39b/packages/tictactoe/src/redux/store.ts#L8

https://github.com/magmo/apps/blob/a3abaf0adcdd4b587b9dbbf97f49bcddd1edb39b/packages/tictactoe/src/redux/store.ts#L20

should  `loginSaga` be `loginRootSaga`?

**Comment by lalexgap** [comment]
> Also:
> 
> [apps/packages/tictactoe/src/redux/store.ts](https://github.com/magmo/apps/blob/a3abaf0adcdd4b587b9dbbf97f49bcddd1edb39b/packages/tictactoe/src/redux/store.ts#L8)
> 
> Line 8 in [a3abaf0](/magmo/apps/commit/a3abaf0adcdd4b587b9dbbf97f49bcddd1edb39b)
> 
>  import loginSaga from './login/saga'; 
> [apps/packages/tictactoe/src/redux/store.ts](https://github.com/magmo/apps/blob/a3abaf0adcdd4b587b9dbbf97f49bcddd1edb39b/packages/tictactoe/src/redux/store.ts#L20)
> 
> Line 20 in [a3abaf0](/magmo/apps/commit/a3abaf0adcdd4b587b9dbbf97f49bcddd1edb39b)
> 
>  yield fork(loginSaga); 
> should `loginSaga` be `loginRootSaga`?

@geoknee Since we export the `loginRootSaga` as default from `./login/saga` it doesn't matter what name we import it as is.
