### ISSUE TITLE
Both players need to be able to close the channel

### ISSUE THREAD

**Issue by tomclose** [magmo/apps#189]
Otherwise, in this state you're basically at the mercy of the other player:

![screen shot 2019-02-11 at 3 43 08 pm](https://user-images.githubusercontent.com/29596/52601507-e1db1b00-2e13-11e9-9d93-b9c67e267800.png)

**Comment by tomclose** [comment]
Also, when I played through to the end, I did actually get stuck in this state ...

**Comment by geoknee** [comment]
@tomclose I suggest for now we simply allow challenging in this game over state (it is currently sort of allowed, only this modal is blocking you clicking the button). I think we should also do this in a way that means you can see the final state of the board. Should be an easy fix to make it look like PlayAgain, only with the button text changed to "Game Over".

I *think* your getting stuck is a bot issue. But please confirm.
