### ISSUE TITLE
Deployed version of rps gets stuck in `A_WAIT_FOR_POST_FUND_SETUP`

### ISSUE THREAD

**Issue by tomclose** [magmo/apps#227]
Steps to reproduce:

1. Go to rps.magmo.com
2. Select a game against a bot
3. Approve funding

Result =  you get stuck on this screen:

<img width="381" alt="screen shot 2019-03-06 at 7 50 12 am" src="https://user-images.githubusercontent.com/29596/53861449-86501780-3fe4-11e9-82a2-a5c25fbd7823.png">

<img width="665" alt="screen shot 2019-03-06 at 7 49 04 am" src="https://user-images.githubusercontent.com/29596/53861470-9cf66e80-3fe4-11e9-9efe-a5335ac81631.png">

```
<meta name="build-version" content="2019-02-12T19:52:10.481Z">
```

**Comment by geoknee** [comment]
This was a bot issue, fixed by redeploying.
