### ISSUE TITLE
Redux directory structure in apps should match the wallet

### ISSUE THREAD

**Issue by kerzhner** [magmo/apps#236]
In apps, the directory structure is: `src\redux\functionality\actions,reducers,state`

In the wallet, the directory structure is `src\redux\actions,reducers,state\functionality`

**Comment by andrewgordstewart** [comment]
👍 👍 

[This extension](https://marketplace.visualstudio.com/items?itemName=stringham.move-ts) (with hotkeys setup) makes this a breeze. However, we should probably wait until the funding refactor is finished.
