### ISSUE TITLE
Errors submitting a transaction

### ISSUE THREAD

**Issue by kerzhner** [magmo/apps#239]
During manual testing, I am seeing the following error when I try to submit a transaction. I am using ganache + chrome for both players:
ALERT: [ethjs-rpc] rpc error with payload {"id":870627856656,"jsonrpc":"2.0","params":["0xf891118504a817c80082b2ec9434d402f14d58e001d8efbe6585051bf9706aa0648711c37937e08000a4f340fa01000000000000000000000000cfc486f817f17fca8c90e17a1c1860ea94a8aeed822d46a07e2ead9589ed04aca4f9f8aeed119837d95827ed7a6fc5a76b67966688538ed0a02e4b71c8f69923c73f6aa60d47a7caf70c7977674412ce02dfcacdd5f651d6fe"],"method":"eth_sendRawTransaction"} Error: the tx doesn't have the correct nonce. account has nonce of: 13 tx has nonce of: 17

**Comment by geoknee** [comment]
I have seen this error before, and it is usually fixed by resetting your metamask account.

**Comment by kerzhner** [comment]
Thanks @geoknee! Would you mind clarifying what you mean by resetting? Toggling the Metamask extension off/on? Or something else?

**Comment by kerzhner** [comment]
Resolved: https://magmo.gitbook.io/reference/developer-handbook/common-development-errors#tx-doesnt-have-the-correct-nonce
