### ISSUE TITLE
Both players stuck in Opening Channel during manual testing on Chrome

### ISSUE THREAD

**Issue by kerzhner** [magmo/apps#240]
![Screen Shot 2019-03-12 at 12.20.26 PM.png](https://zube.io/files/magmo/9205c3b08663de834af9734fed03e9f2-screen-shot-2019-03-12-at-12-20-26-pm.png)

**Comment by kerzhner** [comment]
Resolved: https://magmo.gitbook.io/reference/developer-handbook/common-development-errors#tx-doesnt-have-the-correct-nonce

**Comment by kerzhner** [comment]
`unhandledAction` is not working properly in the `default` case of FundingReducer. An example problem line is https://github.com/magmo/apps/blob/as-split-wallet-redux-state/packages/wallet/src/redux/reducers/channels/funding.ts#L454

**Comment by andrewgordstewart** [comment]
`unhandledAction` doesn't exist anymore
