### ISSUE TITLE
Handle an invalid message nicely

### ISSUE THREAD

**Issue by kerzhner** [magmo/apps#27]
Currently if the app receives an invalid message we simply throw an error and the app stops working. We should show a message to the user.

**Comment by lalexgap** [comment]
Messages are currently validated `const validMessage = yield validateMessage(data, signature);` If a message is invalid we throw an error that we do not nicely handle right now

**Comment by lalexgap** [comment]
This will probably be tackled under magmo/apps#61 

I'll leave as is for now and update once magmo/apps#61  is completed.
