### ISSUE TITLE
During Wallet Initialization store Consensus Library Address in state

### ISSUE THREAD

**Issue by lalexgap** [magmo/apps#294]
We'll need to store the address for the consensus rules in our state somewhere and set it in the initializing process once we know the current network id.

**Comment by lalexgap** [comment]
@geoknee This might be a good one to tackle if you're blocked on the creating the UI.

**Comment by andrewgordstewart** [comment]
I'm not sure we actually want to do this. IIRC, we had decided that `networkID` should be an environment variable. In that case, rather than doing work that we know we will undo with later work, why not do the later work now?

**Comment by tomclose** [comment]
Agree with @andrewgordstewart on this. Probably worth seeing if we can make both of these environment variables at this point.

**Comment by lalexgap** [comment]
If we go with the approach of env variables we should probably pull out the adjudicator address to a fixed environment variable and remove the Adjudicator loading logic as well, since the adjudicator address is fixed as well.

To push these into environment variables we'll need to:
- Improve our scripting to parse JSON contract artifacts.  If the ConsensusLibrary environment variable is not defined we're going to want to populate it based on the json artifacts.
- Start ganache with a fixed network ID (if the network ID environment variable is set)
- Remove adjudicator loading logic (optional but it seems strange that we would load one library address dynamically and one from a environment variable)
