### ISSUE TITLE
Handle message from Player A before Player B has started indirect funding process.

### ISSUE THREAD

**Issue by lalexgap** [magmo/apps#296]
Starting where neither Player A or Player B app has requested funding.
- Player A's app requests funding and player A approves.
- Player A's sends a message to Player B's wallet.
- Player's B wallet has not started the `indirectFunding` process yet so the message is ignored.

Similiar to [#692 (magmo/apps#295)](https://zube.io/magmo/apps/c/692) however this occurs before Player B has started `indirectFunding` at all.

**Comment by kerzhner** [comment]
Per conversation in the standup:

The scenario described in this card is an example of a need for a pattern for the following more general scenario. The general scenario is:
- Two or more conditions need to be satisfied before the state machine can be progressed to the a certain state.
- Each condition is satisfied by an independent action, and actions can arrive in any order.

Initially, our approaches to solving this have been:
- Start in a state that blocks until the first condition is satisfied.
- If second (or subsequent) condition becomes satisfied, stash that information.
- Once the first condition is satisfied, move on to a second state that blocks on the second condition. That state reads the stashed information from the first state.
- Repeat the process for all subsequent conditions.

Or alternatively:
- Start in a state that blocks until the first condition is satisfied.
- If second (or subsequent) condition becomes satisfied, stash that information.
- Once the first condition is satisfied, check stashed information and figure out if second state should be skipped. If the second state is to be skipped, check if the third state needs to be skipped. And so on.

The above approaches have been fragile and difficult to understand. One proposal for a new pattern (already used in parts of the code base) is:
- Create **one** state that has one property for each condition.
- When a condition is met, update the property on the state.
- When all conditions are met, move on to a new state.

**Comment by kerzhner** [comment]
@geoknee @andrewgordstewart @lalexgap @tomclose ^^^. Not sure this if this is the best place to have this documentation.

**Comment by geoknee** [comment]
@kerzhner thanks a lot for this! I will CC it to our dev handbook, where most of our design choices are being documented

**Comment by kerzhner** [comment]
@geoknee Ok great. Zube card ephemeral, so this comment will disappear into the ether soon.

**Comment by andrewgordstewart** [comment]
@geoknee I would not put this in the dev handbook until we've sorted out how we actually deal with this kind of situation.
