### ISSUE TITLE
Clean up FundingState/DirectFunding reducers

### ISSUE THREAD

**Issue by lalexgap** [magmo/apps#305]
Currently `fundingState` was designed to handle both `directFunding` and `indirectFunding` however that no longer applies.
We should:
- remove IndirectFunding logic.
- consolidate `fundingState` and `directFunding` reducers into one.
- Define `directFundingRequested` in a local actions file (instead of using an `internalAction`).

**Comment by kerzhner** [comment]
@lalexgap @andrewgordstewart Wait, so is `fundingState` becoming `directFundingState`?

**Comment by kerzhner** [comment]
Also, should `directFunding` be yet another process?

**Comment by andrewgordstewart** [comment]
There does need to be a `direct-funding` process, but there also needs to be a place to store direct funding related state during the `indirect-funding` process.

I don't know if `fundingState` will become `directFundingState`. That's part of this task, I guess.

**Comment by andrewgordstewart** [comment]
Thinking about our morning conversation, it might make sense to have a `directFunding` branch on the `channelState` branch that the current `directFundingReducer` updates.

Then, a `directFunding` branch on the root level manages the `direct-funding` process (which is very straightforward)
