### ISSUE TITLE
Duplicate messages will be sent out due to the channelReducer and IndirectFundingReducer being responsible for messages.

### ISSUE THREAD

**Issue by lalexgap** [magmo/apps#315]
Currently both the IndirectFundingReducer and the channelReducer will send out PostFundSetup messages, resulting in duplicate messages being sent.
The problem occurs when (assuming we're Player A):
- IndirectFundingReducer receives direct funding and crafts a PostFundSetup commitment message for the ledger channel.
- IndirectFundingReducer then attempts to update the ledger channel state. This means passing the latest ledger channel commitment to the `channelReducer` . The `channelReducer` logic then crafts a PostFundSetup of its own and sends it out.

Currently messaging responsibility is spread across both the channelReducer and the IndirectFundingReducer which causes these issues. Ideally this would be the responsibility of either the IndirectFundingReducer *or* the channelReducer not both.

**Comment by andrewgordstewart** [comment]
One proposal is that the channelState reducer alone is responsible for sending commitments.

**Comment by kerzhner** [comment]
I am in favor of channelState reducer sending out these types of commitments.

I guess the deeper discussion is what are the responsibilities of a channelState reducer vs the indirect funding process reducer. One approach is for channelState reducer to contain as little logic as possible. Another approach is for channelState reducer to create commitments whenever a commitment is a function of channelState of a single channel.

**Comment by lalexgap** [comment]
A few thoughts:

- `Commitment` messages now include a `procedure` (`IndirectFunding`,`DirectFunding`). So if the channel Reducer is responsible for sending these messages it will need to have knowledge of the channel's procedure (which it doesn't have now)
- Right now prefundsetups and postfundsetups are handled very differently. The channel reducer expects that the prefundsetups will be exchanged by the app or the indirectFundingReducer while post fund setups are crafted and exchanged by the channel reducer.  If we want to make the channelReducer solely responsible for crafting commitments it will have to take over responsibility for sending prefund commitments.

**Comment by tomclose** [comment]
Resolution: channel state shouldn't send out post fund setup.
