### ISSUE TITLE
Create Challenging Protocol

### ISSUE THREAD

**Issue by lalexgap** [magmo/apps#348]
We need to create a protocol that is responsible for creating challenges on chain for both the ledger channel and application channel.

The protocol must:
- Register a challenge on chain for the ledger channel.
- Register a challenge on chain for the application channel.
- Wait for either the challenge timeouts or a challenge responses.
- On timeout we need to initiate some sub-protocol to handle the withdrawing the funds.

We will have to handle the cases where we only receive one challenge response and one challenge expires.

**Comment by tomclose** [comment]
In general you don't have to have a challenge in the ledger channel to challenge in the app. You'd probably want to wait until the app challenge has resolved one way or the other and only then challenge in the ledger channel if it's necessary.
