### ISSUE TITLE
Protocol for responding to a challenge

### ISSUE THREAD

**Issue by tomclose** [magmo/apps#356]
Write a protocol for responding to a challenge. To include:

* Deciding which options (respond/refute) are valid
* Getting confirmation from the user to launch a response
* Submitting the response transaction to the blockchain.
* Getting acknowledgement from the user before returning to app
* Returning to the app to make a move if required.

Out of scope (for now)

* Respond with alternative move

TODO:

- [ ] readme / state machine
- [ ] states
- [ ] actions
- [ ] test scenarios
- [ ] reducer
- [ ] reducer tests
- [ ] basic views
- [ ] stories

**Comment by lalexgap** [comment]
Discussed with @tomclose. Out of scope asking for move from application.
