### ISSUE TITLE
Protocol for funding a channel

### ISSUE THREAD

**Issue by tomclose** [magmo/apps#358]
Write a protocol for funding a channel. To include:

* Should be triggered by the `FUNDING_REQUESTED` event from the app.
* Asking the user to confirm they want to fund the channel
* [Handle case where protocol proposal arrives before they have accepted]
* Sending a "protocol proposal" message to the opponent + waiting for confirmation
* Launching the indirect funding protocol
* Send out the post fund setup and wait for the return
* Asking the user to confirm success and return to the app
* Send `FUNDING_SUCCESS` message to app

Out of scope (for now):

* Supporting protocols other than indirect funding

Note: we will need to treat player A and player B separately here, as A proposes the protocol and B responds.

TODO:

- [x] readme: state machine + sequence diagram
- [x] states
- [x] actions
- [x] test scenarios
- [ ] reducer
- [x] reducer tests
- [ ] basic views
- [x] stories

**Comment by kerzhner** [comment]
@andrewgordstewart It might be worth it to close this card and create follow up cards for the remaining work.
