### ISSUE TITLE
Storybook doesn't run on master

### ISSUE THREAD

**Issue by tomclose** [magmo/apps#371]
After merging https://github.com/magmo/apps/pull/368 (at least, I'm assuming this is the culprit) storybook won't run on master (for me).

The error that storybook fails with is:
```
ERROR in ./src/utils/contract-utils.ts
Module not found: Error: Can't resolve '../../build/contracts/ConsensusApp.json'
```
When I try doing a `yarn start` to build the contract, that fails with:
```
DATA:  Compiling ./contracts/Consensus.sol...

DATA:
Compilation warnings encountered:

// loads of warnings ...

DATA:  Error: Returned values aren't valid, did it run Out of Gas?
```

I'm using the following temporary fix on my branch to get storybook to run again: https://github.com/magmo/apps/commit/01b972c095d5f0c9cec4932c5deee8d1ac20363c.

**Comment by lalexgap** [comment]
@tomclose This looks like it might be caused by an underlying bug in web3. I'm going to try and upgrade the version of truffle to hopefully address this.

In the meantime can you try `rm -rf build/contracts` then do a `yarn start`?
