### ISSUE TITLE
Suppress eth_blockNumber messages when running the wallet

### ISSUE THREAD

**Issue by kerzhner** [magmo/apps#44]

**Comment by lalexgap** [comment]
`eth_BlockNumber` is coming from the instance of ganache that gets started up if no instance is running. 

If you run a separate instance of `ganache` then you wouldn't see these message when running the wallet.

We could just start `ganache` with the `-q` flag but that will probably hide all log output (maybe that's ok?).

**Comment by kerzhner** [comment]
Thanks @lalexgap. My thinking is that it is probably too dangerous to suppress all messages with young software like Ganache.
