### ISSUE TITLE
Configure CircleCI to only build/test changed packages

### ISSUE THREAD

**Issue by geoknee** [magmo/apps#454]
https://medium.com/@reuvenharrison/using-circleci-with-monorepos-c04b03f9f39c

**Comment by andrewgordstewart** [comment]
[`lerna run test --since master`](https://github.com/lerna/lerna/tree/master/core/filter-options#--since-ref) should work, but I haven't put the time into determining exactly how it works

**Comment by geoknee** [comment]
Thanks: I was looking at doing it with the circleci configuration itself, but if we can get lerna to do it that could be much simpler. Will investigate further.

**Comment by andrewgordstewart** [comment]
It probably has something to do with all the packages other than `magmo-client-wallet` being private.

**Comment by geoknee** [comment]
Yes I wondered that too. On the other hand, it seems to work on my machine (but not yet on the CI server)...

**Comment by geoknee** [comment]
I think `lerna success run No packages found with the lifecycle script 'test:ci' ` is exactly what you expect unless something has changed from master. 

If you make a trivial change to a file inside one of the packages, it will run the tests in that package.
