### ISSUE TITLE
Redux state upload doesn't work with the wallet overlay

### ISSUE THREAD

**Issue by kerzhner** [magmo/apps#46]
Steps to repro:
1. Get player A to the "Fund your channel" step.
2. Download redux states for the app and the wallet.
3. Refresh the page and upload both states.

Expecting:
![Screen Shot 2019-01-22 at 6.00.34 PM.png](https://zube.io/files/magmo/090651886111905cdfbbc559786e4a93-screen-shot-2019-01-22-at-6-00-34-pm.png)

Instead seeing:
![Screen Shot 2019-01-22 at 6.01.22 PM.png](https://zube.io/files/magmo/3b91fe23d83708d0f1c63e727701bfc8-screen-shot-2019-01-22-at-6-01-22-pm.png)

**Comment by kerzhner** [comment]
It looks like after an upload the modal is part of the page, but not shown properly

**Comment by kerzhner** [comment]
We probably need to add a 'visible' property to the redux store.

**Comment by lalexgap** [comment]
This might be slightly tricky because `visibility` state would have to be maintained in `rps` but currently it's handled by eventhandlers added when the iFrame is created so `rps` doesn't have to think about wallet visibility:
```window.addEventListener('message', (event => {
    if (event.data && event.data.type && event.data.type === SHOW_WALLET) {
      iFrame.style.display = 'initial';
      document.body.style.overflow = 'hidden';
      iFrame.width = '100%';
      iFrame.height = '100%';
    }
    if (event.data && event.data.type && event.data.type === HIDE_WALLET) {
      iFrame.style.display = 'none';
      document.body.style.overflow = 'initial';
      iFrame.width = '0';
      iFrame.height = '0';

    }
  }));```

**Comment by lalexgap** [comment]
I should add the reason we have to handle this in `rps` is that iFrames from a different domain aren't allowed to alter the parent DOM. so the iFrame doesn't have the ability to hide itself because it cannot set the style on the iFrame element.

**Comment by kerzhner** [comment]
How opposed are you to the app explicitly showing and hiding the wallet? Debugging wallet screens is more burdensome when redux upload doesn't fully restore page state.

**Comment by lalexgap** [comment]
The reason I avoided doing that was to prevent consumers of the wallet having to worry about the display aspect of the wallet, so the wallet is more of a turnkey solution.

That being said it might make more sense to just let the app control visibility of the wallet so the wallet doesn't have to worry that it hides/shows in all kinds of layouts. (right now if you resize the screen small enough the wallet doesn't display properly). 

We could also expose optional helper methods that do what we're doing now to handle visibility in the `wallet-client` so users don't have to implement visibility if they don't want (maybe?)
