### ISSUE TITLE
Wallet Build Fails if `lib` is not empty

### ISSUE THREAD

**Issue by lalexgap** [magmo/apps#534]
If the `lib` folder is not empty than the wallet build command fails with these errors: ```error TS5055: Cannot write file '/Users/alexgap/code/apps/packages/wallet/lib/src/redux/protocols/withdrawing/states.d.ts' because it would overwrite input file.

error TS5055: Cannot write file '/Users/alexgap/code/apps/packages/wallet/lib/src/redux/state.d.ts' because it would overwrite input file.

error TS5055: Cannot write file '/Users/alexgap/code/apps/packages/wallet/lib/src/redux/types.d.ts' because it would overwrite input file.

error TS5055: Cannot write file '/Users/alexgap/code/apps/packages/wallet/lib/src/redux/utils.d.ts' because it would overwrite input file.

error TS5055: Cannot write file '/Users/alexgap/code/apps/packages/wallet/lib/src/utils/hex-utils.d.ts' because it would overwrite input file.

error TS5055: Cannot write file '/Users/alexgap/code/apps/packages/wallet/lib/src/utils/reducer-utils.d.ts' because it would overwrite input file.

Found 76 errors.```

**Comment by andrewgordstewart** [comment]
Is it fine to just `clearLib` before running `build`?

**Comment by lalexgap** [comment]
It turns out this was due to references that resolved to the `lib` folder added by vscode's auto import.
