### ISSUE TITLE
Change Resign to Conclude?

### ISSUE THREAD

**Issue by kerzhner** [magmo/apps#55]
Resign is not part of the language of our state machine. It would be nice for the UI to be consistent with the way we think about our code.

**Comment by lalexgap** [comment]
Personally I like `Resign` better here as it feels like a more natural word for quitting a game partway through then `conclude`.

That said I'm not too fussed either way.

**Comment by kerzhner** [comment]
Ok cool, just wanted to see how others felt. Let's keep resign for now.
