### ISSUE TITLE
Sanitize Contract Artifacts

### ISSUE THREAD

**Issue by lalexgap** [magmo/apps#58]
Currently our prebuilt artifacts for the testnets contain hard coded paths to my local machine. We only use the `abi`, `networks` and `bytecode` section from these artifacts so we can sanitize the other information out.

**Comment by lalexgap** [comment]
When someone does this they should verify that they can still run the app against the test net since none of our build/test process will catch this until it blows up once deployed to prod.

**Comment by geoknee** [comment]
This should be absorbed into the workflow described here https://magmo.gitbook.io/developer-handbook/pre-deploying-contracts-to-testnets .
