### ISSUE TITLE
Re-Using Existing Ledger Channel Does not Preserve Funds

### ISSUE THREAD

**Issue by lalexgap** [magmo/apps#671]
Whenever you fund a game using an existing ledger channel, it will not preserve funds properly.

For example if you have L=[A:10,B:10] and want to fund X=[A:5,B:5] you end up with L=[X:10], which loses 10 eth. Instead we should end up with L=[X:5,A:5,B:5].

**Comment by andrewgordstewart** [comment]
Should there be some kind of a sanity check added to [`pushCommitment`](https://github.com/magmo/apps/blob/afc0903e44d28dd4b52b1348ceb12d4f222970c0/packages/wallet/src/redux/channel-store/channel-state/states.ts#L57) that checks the network's total allocation?
