### ISSUE TITLE
Apply recent fixes from rps to ttt

### ISSUE THREAD

**Issue by kerzhner** [magmo/apps#73]

**Comment by kerzhner** [comment]
@geoknee Do you think we still need this card? This was copied from the TTT zube project during the Zube migration.

**Comment by geoknee** [comment]
It might serve as a useful reminder. On the other hand, if we make sure that 

- all the relevant fixes that have been made have their own card
-  future changes to rps (where appropriate)
-- also get made to ttt, or
-- a new ttt card is made

Then this card could be closed.
