### ISSUE TITLE
Get challenge -> expire -> withdraw working

### ISSUE THREAD

**Issue by kerzhner** [magmo/apps#81]
#### RPS and TTT

For Player A (Xs) and Player B (Os).

#### TTT
Possibly also for Player A (Os) and Player B (Xs).

**Comment by geoknee** [comment]
This is apparently a wallet problem.

**Comment by lalexgap** [comment]
@geoknee This was caused by the wallet hiding itself after a challenge expiry is acknowledged. This is now fixed in the `wallet` and now works for `rps`. I'll leave this open for `ttt`
