### ISSUE TITLE
Wallet doesn't handle rejected transaction

### ISSUE THREAD

**Issue by andrewgordstewart** [magmo/apps#98]
From the RPS app, If I reject a transaction from the metamask page, I get the following uncaught error:
`MetaMask - RPC Error: Error: MetaMask Tx Signature: User denied transaction signature.`

I am then redirected to the Magmo wallet welcome screen, with no possibility to go back to the RPS app.

**Comment by andrewgordstewart** [comment]
![rejected-transaction](https://user-images.githubusercontent.com/8432675/51868436-48881100-230b-11e9-84e3-013f01864320.gif)

**Comment by lalexgap** [comment]
This will be handled under magmo/apps#16

**Comment by lalexgap** [comment]
Reopening this as it's more specific than magmo/apps#16 .

Going to shelf magmo/apps#16  for now.
