### ISSUE TITLE
Unhandled error when contracts aren't deployed

### ISSUE THREAD

**Issue by andrewgordstewart** [magmo/apps#99]
We probably won't let the deployed app get to this state, but we don't handle the case when fmg-core contracts aren't deployed:
```
index.js:1 uncaught at rootSaga at rootSaga 
 at loginRootSaga 
 at loginStatusWatcherSaga 
 at loginStatusWatcherSaga 
 TypeError: Cannot read property 'address' of undefined
```
([here](https://github.com/magmo/apps/blob/master/packages/rps/src/redux/login/saga.ts#L69))

**Comment by lalexgap** [comment]
I think this might also happen if you have the wrong network selected?

Ideally we'd want to move this logic into the wallet but a for a short term fix we can just handle this error gracefully in `rps` and `ttt`
